# Generated by Django 5.0.1 on 2024-01-27 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HOSPITAL_APP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departments',
            old_name='dep_decription',
            new_name='dep_description',
        ),
    ]
